# Generated by Django 4.1.1 on 2022-11-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('work_class', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('work_time', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=250)),
                ('created_date', models.DateField()),
            ],
        ),
    ]
