# Generated by Django 4.1.1 on 2022-11-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobs',
            table='jobs',
        ),
    ]
