# Generated by Django 4.1.1 on 2022-11-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('repeat_password', models.CharField(max_length=20, verbose_name='Repeat passord')),
                ('is_agree', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
